[package]
name = "openapi"
version = "1.0.1-pre.0"
authors = ["blah+oapicf@cliffano.com"]
description = "OpenAPI v3 specification and a set of generated API clients for iplocation.net"
license = "MIT"
edition = "2021"

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
serde_repr = "^0.1"
url = "^2.5"
uuid = { version = "^1.8", features = ["serde", "v4"] }
reqwest = { version = "^0.12", features = ["json", "multipart"] }
